### ISSUE TITLE
Missing convey/m4 files?

### ISSUE THREAD

**Issue by davidozog** [jdevinney/bale#4]
After commit d48a15594d02822b6efd3d9ed026d8b463feb50b there appear to be missing files in the `convey/m4` directory.  For instance, `ax_check_compiler_flags.m4`, `acx_pthread.m4`, `doxygen.am`, and possibly more.  Is it possible these files were omitted from that commit?

The issue may be related to the toplevel `.gitignore` file, which apparently excludes all `m4/` directories recursively.  For instance, I added my own copies of `ax_check_compiler_flags.m4` and `ax_pthread.m4` (from gnu.org) to see if I could fix the problem, but I see that those files are ignored by git.

Side note: the error I saw leading to this was:
```
configure.ac:68: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

but that error might be misleading... I think it's due to the missing `ACX_PTHREAD` macro.

**Comment by jdevinney** [comment]
Thanks for letting us know! I think I fixed this issue. Let me know if it's still a problem.

**Comment by davidozog** [comment]
Thanks very much!  This issue is fixed, but I have another build problem that I'll open up in a separate ticket.
